# Toggles the /balance command
# Useful if you have other plugins that use Vault that already have a balance command
enable-balance-command: true

# Here is where all of your quests are held
quests:
  # In this category, KILL quests are stored
  # Kill quests involve needing to kill a certain amount of entities to complete the quest
  kill:
    # Here are some examples (kill quests must follow this format)
    zombie-slayer: # Quest ID - Can be whatever you'd like, but make it descriptive to the quest
      name: Zombie Slayer # Name - This will be displayed on the quest menu
      description: Kill a zombie! # Description - This will also be displayed on the quest menu
      reward: 100 # Reward - How much money they get for the quest
      target: # This category MUST be named target
        type: ZOMBIE # Type - The type of entity, in all caps, that the player needs to kill (use underscores instead of spaces if name is multiple words long)
        count: 1 # Count - How many of this entity the player needs to kill
    # With everything set up, your kill quests should look like this:
    genocide:
      name: Genocide
      description: Kill 5 villagers!
      reward: 420
      target:
        type: VILLAGER
        count: 5
  # Item quests involve needing to collect a certain amount of items to complete the quest
  item:
    # Here are some examples (item quests must follow this format)
    diamond-collector:
      name: Diamond Collector
      description: Collect 24 diamonds!
      reward: 1000
      target:
        material: DIAMOND
        count: 24