name: QuestNPC
version: '${project.version}'
main: dev.potato.questnpc.QuestNPC
api-version: '1.20'
depend:
  - ProtocolLib
  - Vault
soft-depend:
  - EssentialsX
authors: [Potato]
description: A simple plugin for spawning NPCs that give you quests!
commands:
  questnpc:
    description: Spawns a quest NPC at the player's location
    usage: /questnpc
    aliases:
      - qnpc
  balance:
    description: Shows the player their current balance
    usage: /balance
    aliases:
      - bal